### ISSUE TITLE
Processing of the texts for the link previews: encoding problem

### ISSUE THREAD

**Issue by Tilmn** [maxhaesslein/eigenheim#1]
Processing of the texts for the link previews seems to have a encoding problem somewhere:
https://tilman.me/post/interview-about-geometry-daily-on-the-day-of-mathematics-istanbul/

Quotes and other special characters show up as weird substitutions.

**Comment by Tilmn** [comment]
It is processed as expected here: https://socialsharepreview.com/?url=https://www.youtube.com/watch?v=MHp5UOlms-4 So the source should not be the problem.

**Comment by maxhaesslein** [comment]
fixed in v.0.1.6 / https://github.com/maxhaesslein/eigenheim/commit/b912a4432264d6c2f2204f8ede389b38423e74e2
